[package]
name = "mutiny"
version = "0.1.0"
license = "MIT"
authors = ["Sam Clements <sam@borntyping.co.uk>"]
description = "Some simple tools that can be used to test process monitoring systems"
repository = "https://github.com/borntyping/mutiny"

[dependencies]
getopts = "*"
term = "*"
psutil = "*"
