[package]
name = "rust-wrecking-ball"
version = "0.0.1"
authors = ["Sam Clements <sam@borntyping.co.uk>"]

[lib]
name = "wrecking_ball"

[[bin]]
name = "memory"

[[bin]]
name = "announce"

[dependencies]
term = "0.1"
psutil = "0.2"
